version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: casino-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=casino-app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casino-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/casino-app
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - JWT_EXPIRES_IN=1d
      - CLIENT_URL=http://localhost:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: casino-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data: